---
jobs:
  build-core:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Install pre-requisites
        run: |
          pacman -Sy --noconfirm make gcc patch tar ca-certificates git \
              rsync curl sudo bash nano coreutils xz ncurses diffutils \
              unzip

      - uses: ocaml/setup-ocaml@5cf913cf7e9f8b5204e6cd218d3b6b96eb30d17c
        with:
          ocaml-compiler: 5.3.0
          opam-disable-sandboxing: true

      - name: Run opam tests
        run: |
          opam --version
          opam list

on: [push, workflow_dispatch]
