---
jobs:
  build-core:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v2
          ocaml-compiler: 5.3.0
          opam-pin: false
          opam-repositories: |
            default: https://github.com/punchagan/opam-repository.git#fix-win-availability
      - name: Run opam tests
        run: |
          opam --version
          opam list
          opam install conf-clang
          clang --version

on: [push, workflow_dispatch]
