---
jobs:
  build-core:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    steps:
      - name: Configure git to allow long paths, disable autocrlf, and set eol to lf
        run: |
          git config --global core.longpaths true
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Make checkout speedy
        run: git config --global fetch.parallel 50
      - name: Configure git safedir properly
        run: git config --global --add safe.directory $(pwd)
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v2
          ocaml-compiler: 5.3.0
          opam-pin: false
          opam-repositories: |
            default: https://github.com/punchagan/opam-repository.git#fix-conf-libcurl-deps
          save-opam-post-run: true
      - name: Run opam tests
        run: |
          opam list
          opam install conf-pkg-config conf-mingw-w64-curl-x86_64
          opam list
          opam install conf-libcurl
on: [push, workflow_dispatch]
