---
jobs:
  build-core:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: ocaml/setup-ocaml@v3
        with:
          cache-prefix: v3
          ocaml-compiler: 5.3.0
          opam-pin: false
          opam-repositories: |
            default: https://github.com/punchagan/opam-repository.git#with-doc-cyclic-dependency
      - name: Run opam tests
        run: |
          opam --version
          opam list
          opam install opam-format --with-doc

on: [push, workflow_dispatch]
